### Cadastrar musica
POST https://localhost:5001/api/music/create
Content-Type: application/json

{
    "musicName" : "Count on me",
    "Genre": "pop",
    "Singer": "Bruno Mars",
    "Release": "2010"
}

### Listar musicas
GET https://localhost:5001/api/music/listMusics


